### ISSUE TITLE
Json writes order in LatLng

### ISSUE THREAD

**Issue by alakiikonen** [jroper/play-geojson#11]
Just curious if this is a feature or a bug :)

LatLng.scala line 29:

<pre>Writes(latLng => Json.arr(<i>latLng.lng, latLng.lat</i>))</pre>

LngLat.scala line 36:

<pre>Writes(m => Json.arr(<i>m.lng, m.lat</i>))</pre>

Shouldn't the LatLng output the coordinates in different order than the LngLat thus LatLng.scala line 29 should be:

<pre>Writes(latLng => Json.arr(latLng.<b>lat</b>, latLng.<b>lng</b>))</pre>

**Comment by muuki88** [comment]
This is a bug! I wonder how this worked on my machine :astonished:

**Comment by muuki88** [comment]
Can you provide a pull request with regression tests?

**Comment by alakiikonen** [comment]
Created pull request with fixed tests

**Comment by jroper** [comment]
It's a feature - it's in that order because that's the order that CRS84 mandates.  See my comment on #15 for more info.
