### ISSUE TITLE
Carmen GeoJSON (a GeoJSON extension)

### ISSUE THREAD

**Issue by bbarker** [jroper/play-geojson#12]
I'd like to add support for the Mapbox [Carmen GeoJSON format](https://github.com/mapbox/carmen/blob/master/carmen-geojson.md), used for geocoding. 

It appears I'd be able to do this by reimplementing the `FeatureCollection` and `Feature` case classes. However, the combination of the `GeoJson` trait being sealed, and probably more importantly, the `GeoFormats` object being private, seems to make it difficult to build on top of this library externally, though I'm welcome to suggestions! Alternatively, if you think this is something that could belong within the existing library, I can go that route, but don't want to waste time creating an unwelcome fork.

Thanks for the suggestions in advance!

**Comment by jroper** [comment]
The problem with extending `FeatureCollection` is that the implicit resolution can get messy, as which writes should be used?  The one for `CarmenFeatureCollection`, or the one for `FeatureCollection`?  Both will work, only one is correct.

What I would suggest is defining a `CarmenFeatureCollection` that has a `FeatureCollection`, but also has the carmen properties, plus a list of `CarmenFeature`, each of which has a `Feature`, but also has the carmen specific properties.

I must say, geojson already provides extension points (eg, the properties map on `Feature`), why carmen didn't try to use the existing geojson extension points to extend it seems just plain silly to me - this would be incredibly easy to implement if it did.
