### ISSUE TITLE
LatLng.latLngFormat is inverted

### ISSUE THREAD

**Issue by JR-Utily** [jroper/play-geojson#25]
Hello,

In my comprehension, LatLng is a format where a couple of coordinate is given as an array, with first element being the latitude and second element being the longitude.

The `Format[LatLng]` given by play-geojson (in au.id.jazzy.play.geojson.LatLng) do the opposite, the first element is expected to be the longitude:

      case Seq(lng, lat) => LatLng(lat, lng)

**Comment by jroper** [comment]
Yes, that's intended, the GeoJSON spec requires them to be in the order longitude, latitude, as stated in section [3.1.1](https://tools.ietf.org/html/rfc7946#section-3.1.1):

> The first two elements are longitude and latitude, or easting and northing, precisely in that order and using decimal numbers.

So the order in the output GeoJSON can't be changed without being incompatible with all other GeoJSON libraries. If you would prefer to have the order in the code match the order in the GeoJSON, then you can use `LngLat` instead:

```scala
val sydney: Feature[LngLat] = Feature(Point(LngLat(151.2111, -33.86)), 
    properties = Json.obj("name" -> "Sydney"))
```

**Comment by JR-Utily** [comment]
The problem is that I'm using a dataset where the Geopoint is litterally an array of latitude, longitude in this order:
https://public.opendatasoft.com/explore/dataset/geoflar-communes-2016/table/ (you can see the order of the geopoint column is not the same as the order in the geoshape column)

As I observed the 2 kinds of array in real life datasets I collected, I thought the two case classes provided by the library was to handle both kind. I did not understand these classes where only to be used for GeoJSON. I do agree this could be a problem for compatibility with GeoJSON, but I just thought it was not allowed to have a Point[LatLng] if the spec ask specifically to have the longitude first.

In current state I just don't understand the use of LatLng if it has the same representation as LngLat, it would have been less misleading to simply use named parameters in LngLat instantiation when the developer really wants to invert the coordinate order in its code.

Thanks anyway, I will add my own implementation of LatLng in my codebase.

**Comment by jroper** [comment]
`LatLng` is provided because in practice, people talk and think in latitude and longitude, not the other way around. Many GIS APIs provide a LatLng class, eg leaflet does exactly the same as we do, this was provided for consistency and to be more natural. I don't know why GeoJSON specifies it to be the opposite way to the way everyone says it, it makes it prone to bugs, like the dataset you point to - that's clearly a bug in their data and not spec compliant.

You could create your own CRS that formats it in reverse order, see the README for an example custom CRS.

**Comment by JR-Utily** [comment]
Thanks again for the great lib and your advice :)
